### ISSUE TITLE
`PytorchStreamWriter failed writing file data/11: file write failed` on merging lora weights back to base model

### ISSUE THREAD

**Issue by freakynit** [mzbac/qlora-fine-tune#1]
Hi, thanks for the awesome work in this repo... really helpful..

Had successfully trained `TheBloke/wizardLM-13B-1.0-fp16` model on `alpaca-clean` dataset. 

Then while merging(notice the use of `device = cuda`):
```
python merge_peft_adapters.py --device cuda --base_model_name_or_path TheBloke/wizardLM-13B-1.0-fp16 --peft_model_path ./output/checkpoint-100/adapter_model --output_dir ./merged_models/
```
got following error (was running on `A100 80GB`):

```
Loading PEFT: ./output/checkpoint-100/adapter_model
Running merge_and_unload
Traceback (most recent call last):
  File "/root/repositories/GPTQ-for-LLaMa/env1/lib/python3.10/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/root/repositories/GPTQ-for-LLaMa/env1/lib/python3.10/site-packages/torch/serialization.py", line 668, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/11: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/repositories/qlora-fine-tune/merge_peft_adapters.py", line 40, in <module>
    main()
  File "/root/repositories/qlora-fine-tune/merge_peft_adapters.py", line 35, in main
    model.save_pretrained(f"{args.output_dir}")
  File "/root/repositories/GPTQ-for-LLaMa/env1/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1845, in save_pretrained
    save_function(shard, os.path.join(save_directory, shard_file))
  File "/root/repositories/GPTQ-for-LLaMa/env1/lib/python3.10/site-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/root/repositories/GPTQ-for-LLaMa/env1/lib/python3.10/site-packages/torch/serialization.py", line 291, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 791718912 vs 791718800
```

Do note that the merged weights are there... I just haven't verified whether they were written to completion or not:
```
ls -al

-rw-r--r-- 1 root root        560 Jun  2 15:10 config.json
-rw-r--r-- 1 root root        137 Jun  2 15:10 generation_config.json
-rw-r--r-- 1 root root 9948740782 Jun  2 15:10 pytorch_model-00001-of-00003.bin
-rw-r--r-- 1 root root  828702848 Jun  2 15:10 pytorch_model-00002-of-00003.bin
```

**Comment by freakynit** [comment]
Following up...

This might be due to disk space issue. Though I had 300GB disk space, so, was not expected.

**Comment by mzbac** [comment]
Hi @freakynit, 
I haven't tried on GPU. The merge script was pretty much copied from https://gist.github.com/TheBloke/d31d289d3198c24e0ca68aaf37a19032, and modified for me to use CPU merge. Maybe you can try the original script.

**Comment by freakynit** [comment]
@mzbac Verified... this was due to disk space issue... I was using `vast.ai` which showed 300GB available disk space on current mount, but, all of it wasn't actually available (due to maybe being shared with other workloads).

As again, thanks for this great repo that properly clubs all the main steps to finetuning using latest qlora technique, merging the adapter layers back, quantizing the merged model and inferencing in one... Worked beautifully.
