### ISSUE TITLE
InvalidHeaderDeserialization during merging

### ISSUE THREAD

**Issue by JayanthBontha** [mzbac/qlora-fine-tune#10]
I finetuned a model and saved the adapter model. When i try to merge it, the base model loads fine but while loading the adapter model i get the following error 
Traceback (most recent call last):
  File "/home/jayanth2921/qlora/merge_peft_adapters.py", line 40, in <module>
    main()
  File "/home/jayanth2921/qlora/merge_peft_adapters.py", line 28, in main
    model = PeftModel.from_pretrained(base_model, args.peft_model_path)
  File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 332, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 629, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 222, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 309, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

I have double checked the file paths. Is the adapter model corrupted?

**Comment by JayanthBontha** [comment]
The safetensor file for some reason is only 48kb. and it looks like this:

(^@^@^@^@^@^@^@{},"__metadata__":{"format":"pt"}}

changing the first bracket to { gives invalid header length. So im assuming the checkpoint didnt save properly? Is there a way to recover anything? I cannot finetune the model from scratch again

**Comment by mzbac** [comment]
I'm afraid that if the checkpoint wasn't saved correctly, there is no way you can recover it. Perhaps you have to retrain it from your previous checkpoint.
